"""Добавлены снапшоты и роли для просмотра

Revision ID: 0d56a6171dc9
Revises: b68c04ff242c
Create Date: 2026-04-14 16:34:08.456848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d56a6171dc9'
down_revision: Union[str, Sequence[str], None] = 'b68c04ff242c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_access_document_id'), 'document_access', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_user_id'), 'document_access', ['user_id'], unique=False)
    op.add_column('documents', sa.Column('content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content')
    op.drop_index(op.f('ix_document_access_user_id'), table_name='document_access')
    op.drop_index(op.f('ix_document_access_document_id'), table_name='document_access')
    op.drop_table('document_access')
    # ### end Alembic commands ###
